[project]
name = "midi-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anywidget[dev]>=0.9.21",
    "marimo[recommended]>=0.18.4",
    "python-dotenv>=1.2.1",
    "wandb>=0.23.1",
    "weave>=0.52.22",
]
